In [4]:
import numpy as np 
from typing import List

In [9]:
def can_unlock_library(keys: List[List[float]], tolerance: float = 1e-10) -> bool:
    """
    Args:
        keys: List of n vectors, each being a list of n floating-point numbers
        precision: Threshold for numerical calculations (default: 1e-10)

    Returns:
        bool: True if keys can unlock the library, False otherwise
    """
    # Convert to numpy array for better numerical operations
    vectors = np.array(keys, dtype=float)
    n_vectors, dimension = vectors.shape
    print("number of vectors =", n_vectors)
    print("number of dimensions =", dimension)
    
    # Check 1: Number of vectors should match the dimension for a basis
    if n_vectors != dimension:
        return False
    print("number of vectors = number of dimensions")
    
    # Check 2: Linear Independence using QR decomposition
    Q, R = np.linalg.qr(vectors.T)

    print("QR Decomposition done")
    print("Q: Orthogonal Matrix is\n", Q)
    print("R: Upper Triangular Matrix\n", R)
    
    diagonal = np.abs(np.diag(R))
    
    # If any diagonal element is close to zero, vectors are linearly dependent
    is_independent = np.all(diagonal > tolerance)
    print("are vectors independent?", is_independent)
    
    return is_independent

In [12]:
def are_vectors_independent(vectors, tol=1e-10):
    """
    Checks if a set of vectors are linearly independent within a given tolerance.

    Parameters:
        vectors (list or np.ndarray): A list or array of vectors.
        tol (float): Tolerance for linear dependence.

    Returns:
        bool: True if the vectors are linearly independent, False otherwise.
    """
    matrix = np.array(vectors)
    rank = np.linalg.matrix_rank(matrix, tol=tol)
    return rank == len(vectors)


In [14]:
are_vectors_independent([[1,0,0], [0,1,0], [0,0,1]])

np.True_

In [16]:
are_vectors_independent([[2,0,0], [0,1,0], [0,0,0]])

np.False_

In [10]:
can_unlock_library([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

number of vectors = 3
number of dimensions = 3
number of vectors = number of dimensions
QR Decomposition done
Q: Orthogonal Matrix is
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
R: Upper Triangular Matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
are vectors independent? True


np.True_

In [8]:
can_unlock_library([
    [2, 0, 0],
    [0, 2, 0],
    [4, 4, 0]
])

number of vectors = 3
number of dimensions = 3
number of vectors = number of dimensions
QR Decomposition done
Q: Orthogonal Matrix is [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
R: Upper Triangular Matrix [[2. 0. 4.]
 [0. 2. 4.]
 [0. 0. 0.]]
are vectors independent? False


np.False_